version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - agent
      - auth
      - customer
      - shopkeeper
      - email-service
      - redis
      - audit-log
  agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: agent
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: auth
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5001:5001"

  customer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: customer
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5002:5002"
  shopkeeper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: shopkeeper
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5003:5003"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: ["redis-server", "--appendonly", "yes"]
  email-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: email-service
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5005:5005"
  audit-log:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: audit-log
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5006:5006"
