version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      # - agent
      - auth
      # - customer
      # - shopkeeper
     

  # agent:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       PROJECT: agent
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=production
  #   ports:
  #     - "5000:5000"
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: auth
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "5001:5001"

  # customer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       PROJECT: customer
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=production
  #   ports:
  #     - "5002:5002"
  # shopkeeper:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       PROJECT: shopkeeper
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=production
  #   ports:
  #     - "5003:5003"

